gpu_id: 0
multi_gpus: True
num_workers: 2
seed: 666
exp_name: 'expVIDEO-NARR-bert'

train:
  model_name: 'hcrn_bert_freezed'
  freeze_bert: False
  lr: 0.0001
  batch_size: 32
  restore: False
  max_epochs: 25
  word_dim: 100 #300
  module_dim: 512
  glove: False
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 1

val:
  flag: True

test:
  test_num: 0
  write_preds: True

dataset:
  name: 'video-narr-bert'
  text_feat: 'video-narr-bert'
  img_feat: 'video-narr'
  question_type: 'none'
  data_dir: '/mnt/disk1/video_narr'
  save_dir: 'results/'